name: Create release

# Triggered when a tag is pushed whose name is a "v" followed by a semantic
# version; for example, "v1.2.3"
on:
  push:
    tags:
      - v*

jobs:
  create-release:
    name:    Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Create release
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag:          ${{ github.ref }}
          release_name: Version $VERSION
